GET http://localhost:4000/roominfo?roomId=laterceraesla

###
POST http://localhost:4000
content-type: application/json

{
   "roomId": "laterceraeslavencina",
   "roomName": "tressssssssssss",
   "isPrivate": true,
   "userName": "cincooooooooo"
}