GET https://back-socket.herokuapp.com
###
POST https://back-socket.herokuapp.com
content-type: application/json

{
   "roomId": "laterceraeslavencina",
   "roomName": "tressssssssssss",
   "isPrivate": true,
   "userName": "cincooooooooo"
}